import { NextResponse } from 'next/server'
import { errorResponse } from '@/lib/http'
import { getFileContent, getDirectory } from '@/lib/github'
import { parseConfig } from '@/lib/config'
import type { Pack, PackSkill, CommunityPack } from '@/lib/types'

// Shape of packs.json (generated by ./generate-packs-json from packs.config.json
// + skills.json). Membership only - live enabled/installed state is joined here.
interface PacksManifest {
  packs?: Array<{
    key: string
    name: string
    description: string
    color: string
    category: string | null
    default_enabled?: string[]
    skills?: Array<{ slug: string; name: string; description: string; category: string }>
  }>
}

interface CommunityManifest {
  packs?: Array<Omit<CommunityPack, 'installedCount'>>
}

/**
 * GET /api/packs - the first-party pack catalog (packs.json) joined with live
 * enabled state from aeon.yml, plus the community registry (skill-packs.json)
 * joined with on-disk installed state. Both manifests are optional; a missing
 * file yields an empty list rather than a 500.
 */
export async function GET() {
  try {
    const config = await getFileContent('aeon.yml')
      .then(r => parseConfig(r.content))
      .catch(() => null)
    const enabledOf = (slug: string) => config?.skills[slug]?.enabled ?? false

    // First-party packs
    let firstParty: Pack[] = []
    try {
      const { content } = await getFileContent('packs.json')
      const manifest = JSON.parse(content) as PacksManifest
      firstParty = (manifest.packs ?? []).map(p => {
        const skills: PackSkill[] = (p.skills ?? []).map(s => ({
          slug: s.slug,
          name: s.name,
          description: s.description,
          category: s.category,
          enabled: enabledOf(s.slug),
        }))
        return {
          key: p.key,
          name: p.name,
          description: p.description,
          color: p.color,
          category: p.category,
          default_enabled: p.default_enabled ?? [],
          skills,
          total: skills.length,
          enabled: skills.filter(s => s.enabled).length,
        }
      })
    } catch { /* packs.json optional */ }

    // Community packs - count how many of each pack's skills exist on disk.
    let community: CommunityPack[] = []
    try {
      const { content } = await getFileContent('skill-packs.json')
      const manifest = JSON.parse(content) as CommunityManifest
      const installed = new Set(
        (await getDirectory('skills')).filter(d => d.type === 'dir').map(d => d.name),
      )
      community = (manifest.packs ?? []).map(p => ({
        ...p,
        installedCount: (p.skills ?? []).filter(s => installed.has(s)).length,
      }))
    } catch { /* skill-packs.json optional */ }

    return NextResponse.json({ firstParty, community })
  } catch (error: unknown) {
    return errorResponse(error, 'Unknown error')
  }
}

// No PATCH: a pack is a lens for browsing/grouping, not a bulk switch. Skills are
// enabled individually via PATCH /api/skills (the per-skill toggle).
